version: "3.7"
services:
  reactserv:
    build: .
    image: qmcgaw/reactserv
    container_name: reactserv
    ports:
      - 8000:8000/tcp
    volumes:
      - ./react:/srv:ro
    environment:
      - TZ=America/Montreal
      - ROOT_URL=/
    restart: always
